name = "luizalvarez-quartz-cloudflareworker-supabase"
main = "src/index.js"
compatibility_date = "2025-01-24"
compatibility_flags = [ "nodejs_compat" ]

[vars]
SUPABASE_URL = "https://udgswbonvjtklarurlxn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..." # Cole a chave pública

route = "luizalvarez-quartz.pages.dev/*"